[package]
name = "kargo-walk"
version.workspace = true
edition.workspace = true

[[bin]]
name = "kargo-walk"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
rayon = { workspace = true }
jwalk = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_yaml_ok = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
indicatif = { workspace = true }
tempfile = { workspace = true }
tokio-stream = { workspace = true }
toml_edit = { workspace = true }
futures = { workspace = true }
directories = { workspace = true }
cargo_metadata = { workspace = true }
regex = { workspace = true }
clap = { workspace = true, features = ["derive", "cargo"] }
once_cell = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
cargo-manifest = { workspace = true }
cargo_toml = "0.22.3"

[dev-dependencies]
assert_fs = "1.1.3"
predicates = "3.1.3"
