[package]
name = "kargo-upgrade"
version.workspace = true
edition.workspace = true

[lib]
name = "kargo_upgrade"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
kargo-plugin-api = { workspace = true }
anyhow = { workspace = true }
rayon = { workspace = true }
jwalk = { workspace = true }
serde = { workspace = true }
serde_yaml_ok = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
indicatif = { workspace = true }
tempfile = { workspace = true }
tokio-stream = { workspace = true }
toml_edit = { workspace = true }
futures = { workspace = true }
directories = { workspace = true }
cargo_metadata = { workspace = true }
regex = { workspace = true }
clap = { workspace = true }
once_cell = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
cargo-manifest = { workspace = true }
semver = { workspace = true }

[dev-dependencies]
assert_fs = { workspace = true }
predicates = { workspace = true }
cargo-nextest = { workspace = true }
