[package]
name = "kargo-mdlint"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
kargo-plugin-api = { workspace = true }
mado = { git = "https://github.com/akiomik/mado.git", branch = "main" }
clap = { workspace = true }
clap_complete = { workspace = true }
globset = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
