[package]
name = "kargo-plugin-builder"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
regex = { workspace = true }
gag = { workspace = true }
kargo-plugin-api = { path = "../kargo-plugin-api" }
